#!/bin/bash
MY_MESSAGE="Hello World"
echo $MY_MESSAGE
MY_SHORT_MESSAGE=hi
echo $MY_SHORT_MESSAGE
MY_NUMBER=1
echo $MY_NUMBER
MY_PI=3.142
echo $MY_PI
MY_OTHER_PI="3.142"
echo $MY_OTHER_PI
MY_MIXED=123abc
echo $MY_MIXED
