MAINTAINER = "Osama <osama.mahmoud@vxlabs.de>"

require conf/distro/poky.conf

DISTRO = "example-distro"
DISTRO_NAME = "example distro"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "example"
SDK_VENDER = "-exampledistro"
SDK_VERSION = "sdkversion"

hostname_pn-base-files = "osama"

DISTRO_FEATURES += "systemd wifi opengl x11"

VIRTUAL-RUNTIME_init_manager = "systemd"
DISTRO_FEATURES:remove = "sysvinit bluetooth pcmcia wayland pulseaudio bluez5 pci ext2 irda nfc ptest 3g"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"

DEFAULT_TIMEZONE = "Africa/Cairo"

#DISTRO_FEATURES:remove ="bluetooth ext2 irda pcmia pci 3g nfc ipv4 ipv6 largefile pcmcia usbgadget usbhost wifi xattr nfs zeroconf x11 vfat seccomp largefile opengl ptest multiarch wayland vulkan systemd pulseaudio gobject-introspection-data ldconfig"